packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  - "@rollup/rollup-linux-arm-gnueabihf@4.64.2"
  - "@rollup/rollup-linux-loong64-gnu@4.64.2"
  - "@rollup/rollup-linux-x64-musl@4.64.2"
